name: iperf3-rs-test

services:
  iperf3rs-server:
    image: iperf3-rs:test
    command: ["iperf3-rs", "-s"]

  upstream-server:
    image: iperf3-rs:test
    command: ["iperf3", "-s"]

  pushgateway:
    image: prom/pushgateway:v1.11.2

  integration:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: iperf3-rs:test
    depends_on:
      - iperf3rs-server
      - upstream-server
      - pushgateway
    command: ["tests/integration/compose.sh"]
