name: iperf3-rs-test

x-pushgateway-environment: &pushgateway-environment
  PUSH_URL: http://pushgateway:9091
  PUSH_JOB: integration
  PUSH_LABELS: test=self

services:
  server-rs:
    image: iperf3-rs:test
    environment:
      <<: *pushgateway-environment
      PUSH_LABELS: test=self,scenario=tcp-server
    command: ["iperf3-rs", "-s", "-i", "1"]
    depends_on:
      - pushgateway

  reference:
    image: iperf3-rs:test
    command: ["iperf3", "-s"]

  pushgateway:
    image: prom/pushgateway:latest

  client-rs:
    build:
      context: .
      dockerfile: Dockerfile
      target: integration-test
    image: iperf3-rs:test
    environment:
      <<: *pushgateway-environment
    depends_on:
      - server-rs
      - reference
      - pushgateway
