name: iperf3-rs-test

services:
  server-rs:
    image: iperf3-rs:test
    command:
      [
        "iperf3-rs",
        "--push-gateway",
        "http://pushgateway:9091",
        "--job",
        "integration",
        "--test",
        "self",
        "--scenario",
        "tcp-server",
        "-s",
        "-i",
        "1",
        "--json-stream",
      ]
    depends_on:
      - pushgateway

  reference:
    image: iperf3-rs:test
    command: ["iperf3", "-s"]

  pushgateway:
    image: prom/pushgateway:latest

  client-rs:
    build:
      context: .
      dockerfile: Dockerfile
      target: integration-test
    image: iperf3-rs:test
    environment:
      PUSH_GATEWAY_URL: http://pushgateway:9091
      JOB_NAME: integration
      TEST_NAME: self
      SCENARIO_NAME: tcp
    depends_on:
      - server-rs
      - reference
      - pushgateway
