# fish completion for iperf3-rs.

complete -c iperf3-rs -s s -l server -d 'Run in server mode'
complete -c iperf3-rs -s c -l client -r -a "(__fish_print_hostnames)" -d 'Run in client mode, connecting to host'
complete -c iperf3-rs -s p -l port -r -d 'Server port to listen on or connect to'
complete -c iperf3-rs -s f -l format -r -a 'k m g t K M G T' -d 'Format to report'
complete -c iperf3-rs -s i -l interval -r -d 'Seconds between periodic throughput reports'
complete -c iperf3-rs -s I -l pidfile -r -d 'Write PID file'
complete -c iperf3-rs -s F -l file -r -d 'Transmit or receive the specified file'
complete -c iperf3-rs -s B -l bind -r -a "(__fish_print_hostnames)" -d 'Bind to the address or interface'
complete -c iperf3-rs -l bind-dev -r -d 'Bind to a network interface'
complete -c iperf3-rs -s V -l verbose -d 'More detailed output'
complete -c iperf3-rs -s J -l json -d 'Output in JSON format'
complete -c iperf3-rs -l json-stream -d 'Output in line-delimited JSON format'
complete -c iperf3-rs -l json-stream-full-output -d 'Output in JSON format with JSON streams enabled'
complete -c iperf3-rs -l logfile -r -d 'Send output to a log file'
complete -c iperf3-rs -l forceflush -d 'Force flushing output at every interval'
complete -c iperf3-rs -l timestamps -r -d 'Emit a timestamp at the start of each output line'
complete -c iperf3-rs -l rcv-timeout -r -d 'Idle timeout for receiving data in milliseconds'
complete -c iperf3-rs -s d -l debug -r -a '1 2 3 4' -d 'Emit debugging output'
complete -c iperf3-rs -s v -l version -d 'Show version information and quit'
complete -c iperf3-rs -s h -l help -d 'Show help and quit'

complete -c iperf3-rs -s D -l daemon -d 'Run the server as a daemon'
complete -c iperf3-rs -s 1 -l one-off -d 'Handle one client connection then exit'
complete -c iperf3-rs -l server-bitrate-limit -r -d 'Server total bit rate limit'
complete -c iperf3-rs -l idle-timeout -r -d 'Restart idle server after seconds'
complete -c iperf3-rs -l server-max-duration -r -d 'Maximum test duration against the server'
complete -c iperf3-rs -l rsa-private-key-path -r -d 'Path to RSA private key'
complete -c iperf3-rs -l authorized-users-path -r -d 'Path to authorized users file'
complete -c iperf3-rs -l time-skew-threshold -r -d 'Time skew threshold for authentication'
complete -c iperf3-rs -l use-pkcs1-padding -d 'Use PKCS#1 padding'

complete -c iperf3-rs -s u -l udp -d 'Use UDP rather than TCP'
complete -c iperf3-rs -l connect-timeout -r -d 'Timeout for control connection setup'
complete -c iperf3-rs -s b -l bitrate -r -d 'Target bitrate'
complete -c iperf3-rs -l pacing-timer -r -d 'Server timing for pacing'
complete -c iperf3-rs -s t -l time -r -d 'Time to transmit for'
complete -c iperf3-rs -s n -l bytes -r -d 'Transmit this many bytes'
complete -c iperf3-rs -s k -l blockcount -r -d 'Transmit this many blocks'
complete -c iperf3-rs -s l -l length -r -d 'Length of buffer to read or write'
complete -c iperf3-rs -l cport -r -d 'Bind to a specific client port'
complete -c iperf3-rs -s P -l parallel -r -d 'Number of parallel client streams'
complete -c iperf3-rs -s R -l reverse -d 'Run in reverse mode'
complete -c iperf3-rs -l bidir -d 'Run in bidirectional mode'
complete -c iperf3-rs -s w -l window -r -d 'Set socket buffer sizes'
complete -c iperf3-rs -s M -l set-mss -r -d 'Set maximum segment size'
complete -c iperf3-rs -s N -l no-delay -d 'Disable Nagle algorithm'
complete -c iperf3-rs -s 4 -l version4 -d 'Only use IPv4'
complete -c iperf3-rs -s 6 -l version6 -d 'Only use IPv6'
complete -c iperf3-rs -s S -l tos -r -d 'Set IP type of service'
complete -c iperf3-rs -l dscp -r -d 'Set IP DSCP value'
complete -c iperf3-rs -s Z -l zerocopy -d 'Use zero-copy send'
complete -c iperf3-rs -l skip-rx-copy -d 'Ignore received messages using MSG_TRUNC'
complete -c iperf3-rs -s O -l omit -r -d 'Omit pre-test seconds'
complete -c iperf3-rs -s T -l title -r -d 'Prefix every output line with this string'
complete -c iperf3-rs -l extra-data -r -d 'Data string to include in JSON'
complete -c iperf3-rs -l get-server-output -d 'Get results from server'
complete -c iperf3-rs -l udp-counters-64bit -d 'Use 64-bit counters in UDP packets'
complete -c iperf3-rs -l gsro -d 'Enable UDP GSO/GRO'
complete -c iperf3-rs -l repeating-payload -d 'Use repeating payload pattern'
complete -c iperf3-rs -l dont-fragment -d "Set IPv4 Don't Fragment flag"
complete -c iperf3-rs -l username -r -d 'Username for authentication'
complete -c iperf3-rs -l rsa-public-key-path -r -d 'Path to RSA public key'

complete -c iperf3-rs -l push.url -r -a 'http://127.0.0.1:9091 http://localhost:9091' -d 'Push interval metrics to a Pushgateway URL'
complete -c iperf3-rs -l push.job -r -a 'iperf3' -d 'Pushgateway job name'
complete -c iperf3-rs -l push.label -r -a 'test= scenario= site= host=' -d 'Add a Pushgateway grouping label'
complete -c iperf3-rs -l push.timeout -r -a '500ms 1s 5s 10s 30s 1m' -d 'Per-request Pushgateway timeout'
complete -c iperf3-rs -l push.retries -r -a '0 1 2 3 5 10' -d 'Retry failed Pushgateway requests'
complete -c iperf3-rs -l push.user-agent -r -d 'HTTP User-Agent for Pushgateway requests'
complete -c iperf3-rs -l push.metric-prefix -r -a 'iperf3' -d 'Prometheus metric name prefix'
complete -c iperf3-rs -l push.interval -r -a '500ms 1s 5s 10s 30s 1m' -d 'Aggregate interval samples before pushing window metrics'
complete -c iperf3-rs -l push.delete-on-exit -d 'Delete this Pushgateway grouping key after the run exits'
